[toolchain]
channel = "nightly-2024-02-03"
components = [
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rustfmt",
  "rust-src",
]
targets = [
  "wasm32-unknown-unknown",
  "thumbv7em-none-eabi",
]
