#cloud-config
groups:
  - ubuntu: [root,sys]
  - composable

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: composable
    gecos: composable
    shell: /bin/bash
    primary_group: composable
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false

package_update: true
package_upgrade: true

packages:
  - python3-pip
  - libedit-dev
  - libncurses5-dev
  - zlib1g 
  - zlib1g-dev 
  - libssl-dev 
  - libbz2-dev 
  - libsqlite3-dev
  - libffi-dev
  - libssl-dev
  - liblzma-dev
  - libreadline-dev

write_files:
  - path: /run/scripts/install.sh
    content: |
      #!/bin/bash

      # install pyenv
      curl https://pyenv.run | bash

      cat >> $HOME/.bashrc << 'EOF'
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      EOF

      pyenv install 3.11.7
      pyenv global 3.11.7
      
      # clone repo
      git clone https://github.com/ComposableFi/composable-vm.git $HOME/composable-vm 
    permissions: '0755'

runcmd:
  - [ su, "composable", "/run/scripts/install.sh" ]

